### ISSUE TITLE
Login error too

### ISSUE THREAD

**Issue by gui-lux** [Spikeedoo/SnooKey#15]
I have an authentication error

```
user@host:~/script/snooKey$ python3 snookey.py 

  /$$$$$$  /$$   /$$  /$$$$$$   /$$$$$$  /$$   /$$ /$$$$$$$$ /$$     /$$
 /$$__  $$| $$$ | $$ /$$__  $$ /$$__  $$| $$  /$$/| $$_____/|  $$   /$$/
| $$  \__/| $$$$| $$| $$  \ $$| $$  \ $$| $$ /$$/ | $$       \  $$ /$$/
|  $$$$$$ | $$ $$ $$| $$  | $$| $$  | $$| $$$$$/  | $$$$$     \  $$$$/
 \____  $$| $$  $$$$| $$  | $$| $$  | $$| $$  $$  | $$__/      \  $$/
 /$$  \ $$| $$\  $$$| $$  | $$| $$  | $$| $$\  $$ | $$          | $$
|  $$$$$$/| $$ \  $$|  $$$$$$/|  $$$$$$/| $$ \  $$| $$$$$$$$    | $$
 \______/ |__/  \__/ \______/  \______/ |__/  \__/|________/    |__/

Welcome to SnooKey v2.0
Waiting for access token...
Enter your Reddit username: <my_username>
Enter your Reddit password: 
Incorrect username/password combo!
Enter your Reddit username: ^CTraceback (most recent call last):
  File "snookey.py", line 129, in <module>
    full_token = get_token()
  File "snookey.py", line 39, in get_token
    username = input("Enter your Reddit username: ").strip()
KeyboardInterrupt
```

As seen here I CTRL + C to quit. I'm pretty sure about my password.

A fix would be appreciated.

**Comment by Spikeedoo** [comment]
Hi! @gui-lux I just made a small patch, try to re-clone the project and let me know if anything comes up.

**Comment by gui-lux** [comment]
Looks like your patch is working, good job ! Note it worked at the 2nd attempt, but rpan works pretty bad on desktop since yesterday.

```
user@host:~/script/spikekey/SnooKey$ python3 snookey.py 

  /$$$$$$  /$$   /$$  /$$$$$$   /$$$$$$  /$$   /$$ /$$$$$$$$ /$$     /$$
 /$$__  $$| $$$ | $$ /$$__  $$ /$$__  $$| $$  /$$/| $$_____/|  $$   /$$/
| $$  \__/| $$$$| $$| $$  \ $$| $$  \ $$| $$ /$$/ | $$       \  $$ /$$/
|  $$$$$$ | $$ $$ $$| $$  | $$| $$  | $$| $$$$$/  | $$$$$     \  $$$$/
 \____  $$| $$  $$$$| $$  | $$| $$  | $$| $$  $$  | $$__/      \  $$/
 /$$  \ $$| $$\  $$$| $$  | $$| $$  | $$| $$\  $$ | $$          | $$
|  $$$$$$/| $$ \  $$|  $$$$$$/|  $$$$$$/| $$ \  $$| $$$$$$$$    | $$
 \______/ |__/  \__/ \______/  \______/ |__/  \__/|________/    |__/

Welcome to SnooKey v2.0
Waiting for access token...
Getting new token...
Enter your Reddit username: <my_username>
Enter your Reddit password: 
Login success!
Subreddit you want to broadcast to: redditsets
Stream title: just a test

ERROR CODE 503
The reddit servers said "NONE SHALL PASS"!  
Make sure you are eligible to stream.  If you are using r/pan make sure you are trying during valid hours.

Press enter to exit...
user@host:~/script/spikekey/SnooKey$ python3 snookey.py 

  /$$$$$$  /$$   /$$  /$$$$$$   /$$$$$$  /$$   /$$ /$$$$$$$$ /$$     /$$
 /$$__  $$| $$$ | $$ /$$__  $$ /$$__  $$| $$  /$$/| $$_____/|  $$   /$$/
| $$  \__/| $$$$| $$| $$  \ $$| $$  \ $$| $$ /$$/ | $$       \  $$ /$$/
|  $$$$$$ | $$ $$ $$| $$  | $$| $$  | $$| $$$$$/  | $$$$$     \  $$$$/
 \____  $$| $$  $$$$| $$  | $$| $$  | $$| $$  $$  | $$__/      \  $$/
 /$$  \ $$| $$\  $$$| $$  | $$| $$  | $$| $$\  $$ | $$          | $$
|  $$$$$$/| $$ \  $$|  $$$$$$/|  $$$$$$/| $$ \  $$| $$$$$$$$    | $$
 \______/ |__/  \__/ \______/  \______/ |__/  \__/|________/    |__/

Welcome to SnooKey v2.0
Waiting for access token...
Working token found!  Continuing...
Subreddit you want to broadcast to: redditsessions
Stream title: another test

YOUR STREAMER KEY: c44e76c7-3228-4441-9393-3c441962f18c
YOU ARE LIVE: https://www.reddit.com/rpan/r/RedditSessions/unccej

Press enter to exit...
```

Thanks again for your work !

**Comment by Villelmo** [comment]
Hey, can you share the link? @gui-lux

**Comment by Spikeedoo** [comment]
@Villelmo if you re-clone the repository it should be up to date. Let me know if you need any help or if this is not working for you.

**Comment by Villelmo** [comment]
@Spikeedoo I re-clone the repository but i get the following error:

```
Welcome to SnooKey v2.0
Waiting for access token...
Working token found!  Continuing...
Traceback (most recent call last):
  File "/home/lulu/SnooKey/snookey.py", line 128, in <module>
    rpan_subreddits_full = subreddit_check.json()["data"]
KeyError: 'data'
```
Where is saved the token?

**Comment by gui-lux** [comment]
Hi @Spikeedoo ,
I guess reddit has changed something, again. Authentication does not work anymore, exact same symptom.
It was working like a month ago.
Thanks a lot for your help.

**Comment by Villelmo** [comment]
So, i can't use OBS Studio. I want to make live streaming in reddit.

**Comment by gui-lux** [comment]
Looks like the trouble was on the reddit side.
Solved
